name: MM_TVPro
description: "Funny Myanmar Movie Project"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_nav_bar: ^5.0.6
  http: ^1.1.0
  connectivity_plus: ^5.0.1
  url_launcher: ^6.1.12
  get: ^4.6.5
  cached_network_image: ^3.2.3
  flutter_spinkit: ^5.2.0
  drift: ^2.11.1
  path_provider: ^2.1.1
  sqlite3_flutter_libs: ^0.5.16
  facebook_audience_network: ^1.0.1
  get_storage: ^2.1.1
  flutter_vlc_player: ^7.4.0
  smooth_page_indicator: ^1.1.0 
  webview_flutter: ^4.4.2
  intl: ^0.19.0
  youtube_player_flutter: ^9.0.1
  cupertino_icons: ^1.0.6
  loading_animation_widget: ^1.2.1 
  wakelock: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  image_path: "assets/images/ic_launcher.png"


  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  assets:
     - assets/images/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

